name: .Net
on:
  push:
    tags:
    - RELEASE
    branches:
    - master
  pull_request:
    branches:
    - master
env:
  IS_RELEASE_CANDIDATE: >-
    ${{
      (
        github.event_name == 'pull_request' &&
        startsWith(github.event.pull_request.title, 'RELEASES:') &&
        contains(github.event.pull_request.labels.*.name, 'RELEASES')
      )
      ||
      (
        github.event_name == 'push' &&
        startsWith(github.event.head_commit.message, 'RELEASES:') &&
        github.ref_name == 'RELEASE'
      )
    }}
jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 0
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Setup .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.1.22110.4
        include-prerelease: true
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
